version: '3.3'

services:
  finance-app:
    image: mysql:8.0.26
    container_name: incit-test-db
    platform: linux/amd64
    volumes:
      - ~/mysql-dump:/docker-entrypoint-initdb.d
      - ~/incit-mysql-db:/var/lib/mysql
    ports:
      - 33907:3306
      - 25100:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=incit_test_db
      - MYSQL_USER=test
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=test
    restart: always
    command: --sql_mode="REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
